#x = 5

try:
    print( x )

except:
    print( "error" )
